### ISSUE TITLE
extension-key is ignored

### ISSUE THREAD

**Issue by steffenk** [FluidTYPO3/builder#110]
when creating providerextension, i get extension with key "1":

./typo3/cli_dispatch.phpsh extbase builder:providerextension --title "corlate" --description "Using corlate template" --use-vhs "1" --pages "1" --content "1" --backend "1" --controllers "1" --git "1" --extension-key "somekey" --author "any author ..."

**Comment by NamelessCoder** [comment]
Hi Steffen,

I think we're enforcing a `Vendor.ExtensionName` format for the extension key in the backend module; and the CLI command should too. I will look into fixing that but in the meantime you should be able to generate using that format.

**Comment by steffenk** [comment]
Hi,

i tried this as well, but still extension key "1"
funny that the extension key was used as author in em_conf:
'author' => 'SkTypo3.corlate',

**Comment by steffenk** [comment]
also it's misleading from docs: an argument is not prefixed with "--", this is used for options. If i try to use --author "..." i get message:
Oops, an error occurred: Unexpected named argument "author". If you use unnamed arguments, all required arguments must be passed without a name.

I tried all possible variations without success.

**Comment by NamelessCoder** [comment]
I'm not sure why that CLI command won't work on your host but testing this on a standard Ubuntu I'm able to run the provider extension generation command with multiple different combinations of arguments and get the expected result. Some of the commands I ran, for your comparison:

```
./typo3/cli_dispatch.phpsh extbase builder:providerextension --extension-key "Foobar.BazExtension"
# above command asks for additional required "author" argument before executing
./typo3/cli_dispatch.phpsh extbase builder:providerextension --extension-key "Foobar.BazExtension" --author "Some Man" --description "Some description" --content 1 --pages 1
./typo3/cli_dispatch.phpsh extbase builder:providerextension --extension-key "Foobar.BazExtension" --description "Some description" --content 0 --author "Some Man"
./typo3/cli_dispatch.phpsh extbase builder:providerextension --extension-key "Some.BadExtension" --author "any author" --title "corlate" --description "Using corlate template" --use-vhs 1 --pages 1 --content 1 --backend 1 --controllers 1
```

I can only guess that something (I'm unable to say what) is causing those arguments to be treated incorrectly. And you should also be experiencing the same problems with other Extbase command controllers - builder really doesn't do anything special when it comes to defining and receiving controller arguments. We declare them, phpdoc-annotate them and then expect them to work.

In any case: boolean arguments must be passed as `0` or `1` and the `--git` argument is no longer supported. Fixing those two aspects of your build command seems to get the job done :)
