### ISSUE TITLE
Uncaught TYPO3 Exception - T3 V8.6.0

### ISSUE THREAD

**Issue by ingeniumdesign** [FluidTYPO3/builder#114]
TYPO3 8.6.0

**Backend-Error**

> Uncaught TYPO3 Exception
Undeclared arguments passed to ViewHelper TYPO3\CMS\Fluid\ViewHelpers\FlashMessagesViewHelper: class

> TYPO3Fluid\Fluid\Core\ViewHelper\Exception thrown in file
/html/typo3/typo3_src-8.6.0/vendor/typo3fluid/fluid/src/Core/ViewHelper/AbstractViewHelper.php in line 456.

**Comment by deadmanIsARabbit** [comment]
Push!

**Comment by stenno** [comment]
So the fluid builder with vhs and flux only works in the LTS 7.6.0? Is there any ETA on when it will work on 8.*, especially 8.7.0?
