### ISSUE TITLE
Static Template file not registered when Provider Extension installed.

### ISSUE THREAD

**Issue by neil-h** [FluidTYPO3/builder#117]
I'm using the current builder development branch on TYPO3 8.7.3.

After creating and installing my provider extension, I didn't have a static template file available to include in my site template.

The solution was to rename `ext_localconf.php` to `ext_tables.php` in my provider extension.

**Comment by kllmanu** [comment]
Thanks, I had the same issue using 9.5, the static template just didn't appear.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/builder/commit/b4ef5c9a9cb3b846d5a85732674fd564788e4e8a
