### ISSUE TITLE
TYPO3 9.5 / vhs 6.0.0 Builder throws error SelectViewHelper class not found

### ISSUE THREAD

**Issue by ghwaldo** [FluidTYPO3/builder#123]
Seems that SelectViewHelper is removed, but is not corrected in VHS documentation.

It is removed due to using the core vieh helper.

So, to get builder up running change the template Backend.html, remove v::form... and use f:form...

**Comment by NamelessCoder** [comment]
Confirmed, but there are several other things that are no longer compatible in terms of building the BE module.

**Comment by ghwaldo** [comment]
Do you have further Infos ?
I changed what I mentioned and flux template got up so far that it showed me the backend I expected.

**Comment by NamelessCoder** [comment]
@ghwaldo In addition to the (easily solved) SelectViewHelper issue, the backend module on TYPO3v10 doesn't look right and contains duplicated or broken "frame" elements such as the top bar with the function menu. It might require a completely different template structure, which implies version conditions (something that should be avoided if at all possible).

**Comment by ghwaldo** [comment]
I think we don't need version conditions as the builder is only used to build the basic provider extension. So the builder-extension could be freezed for 9.5.x and a new branch should be startet for > 10,x.
Or do you speak about FLUX ? Or speak about a builded provider extension ?

**Comment by NamelessCoder** [comment]
EXT:builder has multiple purposes beyond generating the extension and contains a backend module implementation which is precisely the part that causes problems. If you try this out on a TYPO3 10.3+ site you should quickly see the problem. Maintaining multiple branches is worse than having a version-based condition so this should also be avoided.

**Comment by ghwaldo** [comment]
OK, as you like.
I think, you don't have to maintain the old version, just freeze it. So anyone can use on 9.x.
But if you like, use version-based conditions.

But i have some questions:
1. Do provider-extensions built by builder on 9.x run on 10.x or can i get infos what i have to do to get it up and running ?

2. The builder also has a command-line interface, or am i wrong ? Does it work under 10.x ?

3. Are there plans getting extension-builder running on 10.x ?

Thnx

**Comment by NamelessCoder** [comment]
> I think, you don't have to maintain the old version, just freeze it.

True temporarily, but only until such a time that changes are required to - for example - the generated extension to match a Flux version that is still marked as compatible with TYPO3v9.

1. They do, but depending on what you actually created, they may require minor adaptations to the metadata that is generated; such as removing dependency on Fluidpages and adjusting core compatibility constraints.
2. Yes, it does. The CLI interface should work on 10.x but the produced extension will require adaptations as described in point 1.
3. Plans, yes. With set date, no.

**Comment by NamelessCoder** [comment]
Solved by https://github.com/FluidTYPO3/builder/commit/b4ef5c9a9cb3b846d5a85732674fd564788e4e8a
