### ISSUE TITLE
[BUGFIX] Required argument "install" is not set.

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/builder#62]
the same problem that with the previous one.
TYPO3 7.1 and builder development version

**Comment by xf-** [comment]
We know that. Development branch isn't v7layout merged yet, because it needs also to be compatible to v6.2 and also some minor stuff needs to be fixed.

**Comment by NamelessCoder** [comment]
Last trace of legacy arguments removed by https://github.com/FluidTYPO3/builder/commit/c8312e2895aea40ff78e7e3480d7c032144aa96b - I hope.
