### ISSUE TITLE
Incorrect syntax for backend icon in generated page template

### ISSUE THREAD

**Issue by mhmli** [FluidTYPO3/builder#63]
Is
`<flux:form id="fluidpage" options="{icon: 'Icons/Page/Standard.gif'}">`

Should be

`<flux:form id="fluidpage" options="{icon: '{f:uri.resource(path: \'Icons/Page/Standard.gif\')}'}">`

(The icon is in the correct location but the backend always shows a broken image link. Per http://stackoverflow.com/questions/28601412/no-backend-icons-fluid-powered-typo3-wrong-path#comment45549655_28623377

**Comment by NamelessCoder** [comment]
Migrated to rely on icon-by-file-path convention.
