### ISSUE TITLE
Fluidbackend is not working by default.

### ISSUE THREAD

**Issue by jmverges** [FluidTYPO3/builder#70]
When I create myprovider extension I'm looking for creating a BackendModule.
![builder creation](https://cloud.githubusercontent.com/assets/2902073/8965461/ffb386dc-362b-11e5-813b-e37e902a7663.png)

All files are created and module is included. However when I click on the module I'm getting:
![exception](https://cloud.githubusercontent.com/assets/2902073/8965469/0b037d58-362c-11e5-894f-e60b3349f793.png)

My first attempt to solve it was change the namespace to
namespace My\Myprovider2\Controller;
and change the register to:
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('My.myprovider2', 'Backend');

then I'm not able to enter in the admin and I'm getting:
![first attempt](https://cloud.githubusercontent.com/assets/2902073/8965597/d8a842c0-362c-11e5-8c9e-480746a05b38.png)

Debugging I'm getting:
![debug](https://cloud.githubusercontent.com/assets/2902073/8965740/9d0a2a2a-362d-11e5-984f-60c0d8328528.png)

is returning null and then it throw the exception:
![dubug2](https://cloud.githubusercontent.com/assets/2902073/8965783/e74fc108-362d-11e5-93bb-02382c139a26.png)

Removing the exception this is a debug screen
![debug3](https://cloud.githubusercontent.com/assets/2902073/8965876/907ba896-362e-11e5-8840-47c0c5ec5b06.png)

The result is
![result](https://cloud.githubusercontent.com/assets/2902073/8965967/e8af3af0-362e-11e5-9035-e8bb024671f7.png)

If anyone can confirm it, could be great.

**Comment by jmverges** [comment]
Well, after having a similar issue with other thing no related I can conclude the following.
This error disappear once I uninstall and install again the extension but I need to use
\FluidTYPO3\Flux\Core::registerProviderExtensionKey('My.Myprovider2', 'Backend');
using \FluidTYPO3\Flux\Core::registerProviderExtensionKey('Myprovider2', 'Backend'); I get the first error.
If you know any way to not uninstall and install an extension or rm -R * typo3temp could be great. If not, I think we should report this to Core because all the clear caches even installation one don't solve it.

On the other hand, maybe we should add a *Vendor field in Builder*

**Comment by NamelessCoder** [comment]
Re: vendor field - yes, either that, or allow using `Vendor.ExtensionName` format like you did :)

Re: need to clear caches... check the ext_emconf.php template file we generate - if it has "clearCacheOnLoad" disabled it's perfectly okay to enable this. That should cause TYPO3 to flush all caches when you first install the extension, in turn causing all the `ext_*` files from the provider extension to be properly (re)loaded.

The other thing we could do, which I wouldn't object to, is add an option for builder's generate command on backend- and CLI-controller which if enabled will flush these caches (via the core API). Feel free to implement if you agree this makes sense!

**Comment by xf-** [comment]
I think this is completed or @jmverges ?

**Comment by jmverges** [comment]
I hope so ;)
