### ISSUE TITLE
Improper plugin.tx_Vendor.MyExtKey. typoscript path in EXT:builder provider extension result

### ISSUE THREAD

**Issue by wikipeter** [FluidTYPO3/builder#81]
I just tested the latest EXT:builder in development branch and realized, the generated typoscript configuration for an extension like Vendor.MyExtKey starts with plugin.tx_Vendor.MyExtKey. which i'm not familiar with.

I expect it to be plugin.tx_my_ext_key.

Did i omit any major change in the TYPO3 Core or is this just wrong?

Regards

Peter

**Comment by xf-** [comment]
hi,

thx for the report.
I think this is a bug, Vendor is import for some namespace stuff and possibility, but not in TS.
