### ISSUE TITLE
Language file for backend module is not created

### ISSUE THREAD

**Issue by igodorogea** [FluidTYPO3/builder#89]
When I create a provider extension and select the option to also generate a backend module,
builder doesn't create a locallang file for it.

That results to a nameless module in backend

**Comment by NamelessCoder** [comment]
Thanks @Ghaniball, we'll investigate.

**Comment by xf-** [comment]
which TYPO3 version?

**Comment by NamelessCoder** [comment]
Every version, @xf-, there's no logic at all to write that file.

**Comment by neufeind** [comment]
Confirmed. The module has no name in the backend.

**Comment by NamelessCoder** [comment]
Backend integration is no longer provided by Flux and EXT:builder no longer generates backend resources.
