### ISSUE TITLE
Documentation not rendered correctly

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/builder#92]
The rendered documentation seems really broken: https://docs.typo3.org/typo3cms/extensions/builder/

**Comment by xf-** [comment]
We use GitHub and markdown and no ReST docu.

**Comment by NamelessCoder** [comment]
What you see on that link is actually the result of TYPO3's own Markdown parsing of the README.md file shipped with extensions. The rendering was introduced quite quickly and I'm sure it's not perfect.

But: to report any issues with markdown rendering on typo3.org you have to report this to the official TYPO3 bug tracker. TER and implicitly the markdown renderer is run by them, not us ;)

**Comment by cweiske** [comment]
Issue for the typo3 server team opened: https://forge.typo3.org/issues/71019
