### ISSUE TITLE
Documentation about what to do when the extension has been created

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/builder#93]
It'd be nice if there was a step-by-step guide what to do after an extension has been created with builder.

For example:
- Creating the page typoscript template
 - including the extension TS into it
- In the root page
 - "Appearance" -> Backend layout needs to be set to "Fluidpages"
 - "Page Layouts" - select the layout
  - as written in the last paragraph on https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/page-template.html and https://fluidtypo3.org/documentation/templating-manual/templating/using-templates/selecting-page-templates.html

should be mentioned there.

**Comment by xf-** [comment]
is documentation and website and not builder. We don't use ReST.

**Comment by cweiske** [comment]
?

**Comment by cedricziel** [comment]
I agree with Christian. Displaying them buttons is only enough when you know what to do.

**Comment by xf-** [comment]
@cedricziel i mean this is more an issue for documentation.
I don't argue about "more information would be useful".

**Comment by cweiske** [comment]
After generating the extension, a link to this documentation should be shown.

**Comment by xf-** [comment]
+1

**Comment by jmverges** [comment]
Guys, basic and typical steps can be done with ext:site. Could be great to explain what is ext:site doing and explain you can do all steps manually or with site. Do you agree?

**Comment by cweiske** [comment]
After using ext:builder to create an extension, why should I install another extension?
The created extension can be used fine without ext:site, so the docs should concentrate on how to use the created extension.

**Comment by jmverges** [comment]
Yep, you are right, however basic configuration steps also can be done with ext:site.

**Comment by NamelessCoder** [comment]
There's no reason why EXT:builder can't link to the official documentation on the "receipt" page. EXT:site can do the same. It can be a plain old hardcoded link to https://fluidtypo3.org/ (without folder) so we don't risk breaking it when updating docs.

**Comment by cweiske** [comment]
Awesome!
