### ISSUE TITLE
Generated content element uses flux:field.inline instead of field.input

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/builder#94]
The generated content element uses `flux:field.inline` inside the configuration section, which renders to nothing in TYPO3 6.2.15.

It should generate a `flux:field.input` element that can actually be used.

**Comment by cweiske** [comment]
Also, when enabling frontend editing, this causes the following fatal error:

    Fatal error: Call to a member function getViewHelper() on null
    in .../typo3temp/Cache/Code/fluid_template/MyFluidTest_Content_action_render_c0944f648354597d7e546dc495725d69b7a21978.php on line 17

**Comment by xf-** [comment]
Worked in last test. v6 support will be dropped soon. (Maybe this is an issue related to flux)
Builder is mainly used in new projects and v7 is released really soon.

**Comment by NamelessCoder** [comment]
Nothing wrong with that, I think. We'd appreciate a pull request with this change!
