### ISSUE TITLE
Generated extension: Flux registration happens in ext_tables.php

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/builder#96]
The manual recommends to put the registration into `ext_localconf.php`:

> On TYPO3 6.2 and above, you only need to add this in ext_localconf.php or ext_tables.php - which one you choose doesn't matter, but for consistency we recommend always using ext_localconf.php. 

https://fluidtypo3.org/documentation/templating-manual/templating/provider-extension/registration-in-php.html

Registration code:

    \FluidTYPO3\Flux\Core::registerProviderExtensionKey('Test.FluidTest', 'Page');
    \FluidTYPO3\Flux\Core::registerProviderExtensionKey('Test.FluidTest', 'Content');

**Comment by neufeind** [comment]
At least the addStaticFile() still needs to be in ext_tables.php. I've tried to move that (just) to ext_localconf.php and it didn't work out. Claus said that for the registration we might need it just in the ext_localconf.php. Imho we should have the code just in one place.
Also note that the function is still called appendExtensionTablesFile() but now touches the ext_localconf.php (additionally). Maybe better clear up where the code needs to go and split that in two functions.
