### ISSUE TITLE
Generated extension: page: flux:grid outside flux:form

### ISSUE THREAD

**Issue by cweiske** [FluidTYPO3/builder#97]
In a generated extension, the page layout's configuration section directly contains the `flux:grid` instead of having it inside flux:form as the documentation recommends:

https://fluidtypo3.org/documentation/templating-manual/templating/creating-templates/page-template.html:
```
<flux:form id="foo">

    [...]

    <!-- Backend layout grid (TYPO3 6.x and greater only) -->
    <flux:grid>
        <flux:grid.row>
            <flux:grid.column colPos="1" name="Sidebar" style="width: 25%" />
            <flux:grid.column colPos="0" name="Content" style="width: 75%" />
        </flux:grid.row>
    </flux:grid>

</flux:form>
```

`Resources/Private/Templates/Page/Standard.html`:

```
<f:section name="Configuration">
	<flux:form id="standard">
	    <!-- Insert fields, sheets, grid, form section objects etc. here, in this flux:form tag -->
            <flux:field.input name="settings.pageClass" default="some-css-class" />
	</flux:form>
	<flux:grid>
	    <!-- Edit this grid to change the "backend layout" structure -->
	    <flux:grid.row>
		<flux:grid.column colPos="0" colspan="3" name="main" />
		<flux:grid.column colPos="1" name="right" />
	    </flux:grid.row>
	</flux:grid>
</f:section>
```

**Comment by xf-** [comment]
generated code is OK - documentation repo

**Comment by NamelessCoder** [comment]
Both usages are actually valid. For cleanliness we recommend putting `flux:form` and `flux:grid` as siblings, like the generated file you quote.

**Comment by NamelessCoder** [comment]
...but docs have not been updated for a while, that's why the online example still nests it. It's not a problem though :)

**Comment by cweiske** [comment]
@NamelessCoder: Docs have not been rendered for a time, or have not been fixed yet?

**Comment by cweiske** [comment]
Apparently it has not been fixed yet; https://github.com/FluidTYPO3/documentation/blob/rewrite/3.Templating/3.2.CreatingTemplateFiles/3.2.2.PageTemplate.md
